<?php
// $Id$

/**
 * @file
 * Main module file for Feedbackify
 */

/**
 * Implementation of hook_help().
 */
function feedbackify_help($path, $arg) {
  switch ($path) {
    case 'admin/help#feedbackify':
      return t('Please use your form ID from your Feedbackify account. Please see http://www.feedbackify.com for a demo and more information.');
  }
}

/**
 * Implementation of hook_menu().
 */
function feedbackify_menu() {
  $items = array();
  $path = drupal_get_path('module', 'feedbackify');

  $items[$path . '/js/feedbackify.js'] = array(
    'title' => 'Feedbackify',
    'page callback' => 'feedbackify_js',
    'type' => MENU_CALLBACK,
    'access arguments' => array(true),
  );

  $items['admin/settings/feedbackify'] = array(
    'title' => 'Feedbackify',
    'description' => 'Configure the Feedbackify.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feedbackify_settings_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'feedbackify.admin.inc',
  );
  return $items;
}


/**
 * Implementation of hook_init().
 */
function feedbackify_init() {
  $path = drupal_get_path('module', 'feedbackify');
  if (variable_get('feedbackify_id', NULL) > 0) {
    drupal_set_html_head('<script type="text/javascript">document.write(\'<scr\' + \'ipt src="\' + document.location.protocol + \'//fby.s3.amazonaws.com/fby.js"></scr\' + \'ipt>\');</script>');
    //Add our custom JavaScript file.
    drupal_add_js($path . '/js/feedbackify.js', 'module');
  }
}

/**
 * Implementation of custom javascript
 */
function feedbackify_js() {
  global $user;
  $feedbackify_id = variable_get('feedbackify_id', NULL);
  $feedbackify_colour = variable_get('feedbackify_colour', '#237BAB');
  
  $output .= 'FBY.showTab({id: \'' . $feedbackify_id . '\', position: \'right\', color: \'' . $feedbackify_colour . '\'});';
  $output = 'Drupal.behaviors.feedbackify = function(context){ ' . $output . '}';
  header('Content-type: text/javascript;');
  echo $output;
  exit();
}