<?php
/**
 * @file
 * Main module file for Feedbackify
 */

/**
 * Implementation of hook_help().
 */
function feedbackify_help($path, $arg) {
  switch ($path) {
    case 'admin/help#feedbackify':
      return t('Please use your form ID from your Feedbackify account. Please see http://www.feedbackify.com for a demo and more information.');
  }
}

/**
 * Implementation of hook_perm().
 */
function feedbackify_perm() {
  return array('administer feedbackify');
}

/**
 * Implementation of hook_menu().
 */
function feedbackify_menu() {
  $items = array();
  $items['admin/settings/feedbackify'] = array(
    'title' => 'Feedbackify',
    'description' => 'Configure the Feedbackify.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feedbackify_settings_form'),
    'access arguments' => array('administer feedbackify'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implementation of hook_footer() to insert Javascript at the end of the page.
 */
function feedbackify_footer() {
  $feedbackify_id = check_plain(variable_get('feedbackify_id', ''));
  $feedbackify_pos = check_plain(variable_get('feedbackify_pos', 'right'));
  $feedbackify_color = check_plain(variable_get('feedbackify_color', '#237BAB'));

  if (!empty($feedbackify_id) && _feedbackify_visibility_pages()) {
    $script = 'document.write(unescape("%3Cscript src=\'" + document.location.protocol + "//fby.s3.amazonaws.com/fby.js\' type=\'text/javascript\'%3E%3C/script%3E"));';
    drupal_add_js($script, 'inline', 'footer');
    
    // print Feedbackify label
    $script = 'FBY.showTab({id: \'' . $feedbackify_id . '\', position: \'' . $feedbackify_pos . '\', color: \'' . $feedbackify_color . '\'});';
    drupal_add_js($script, 'inline', 'footer');
  }
}

/**
 * Implementation of Feedbackify settings form
 */
function feedbackify_settings_form() {
  $form = array();
  $form['feedbackify_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Feedbackify form ID'),
    '#default_value' => variable_get('feedbackify_id', NULL),
    '#required' => TRUE
  );

  $form['feedbackify_color'] = array(
    '#type' => 'textfield',
    '#title' => t('Button color'),
    '#default_value' => variable_get('feedbackify_color', '#237BAB'),
    '#description' => t('Please specify a hexadecimal color value like %color, or leave blank for transparent.', array('%color' => '#237BAB'))
  );

  $form['feedbackify_pos'] = array(
    '#type' => 'select',
    '#title' => t('Button Position'),
    '#default_value' => variable_get('feedbackify_pos', 'right'),
    '#options' => array(
      'left' => t('Left'),
      'right' => t('Right')
    ),
  );
  
  $options = array(t('On every page except the listed pages.'), t('On the listed pages only.'));
  $description = t("Enter one page per line as Drupal paths. The '*' character is a wildcard. Example paths are %blog for the blog page and %blog-wildcard for every personal blog. %front is the front page.", array('%blog' => 'blog', '%blog-wildcard' => 'blog/*', '%front' => '<front>'));
  $pages = variable_get('feedbackify_pages', '');
  $visibility = variable_get('feedbackify_visibility', 0);

  $form['feedbackify_visibility_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Page specific settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['feedbackify_visibility_settings']['feedbackify_visibility'] = array(
    '#type' => 'radios',
    '#title' => t('Display Feedbackify button'),
    '#options' => $options,
    '#default_value' => $visibility,
  );
  $form['feedbackify_visibility_settings']['feedbackify_pages'] = array(
    '#type' => 'textarea',
    '#title' => t('Pages'),
    '#default_value' => $pages,
    '#description' => $description,
    '#wysiwyg' => FALSE,
  );
  return system_settings_form($form);
}

/**
 * Settings form validate handler to ensure a hexadecimal color value.
 */
function feedbackify_settings_form_validate($form, &$form_state) {
  if (!empty($form_state['values']['feedbackify_color'])) {
    if (!preg_match('/^#[0-9a-fA-F]{3}([0-9a-fA-F]{3})?$/', $form_state['values']['feedbackify_color'])) {
      form_error($form, t('Button color must be a hexadecimal color value like %color, or left blank for transparent.', array('%color' => '#237BAB')));
    }
  }
}

/**
 * Function to determine if the Feedbackify code should be printed on the current page
 */
function _feedbackify_visibility_pages() {
  $visibility = variable_get('feedbackify_visibility', 0);
  $pages = variable_get('feedbackify_pages', '');

  // Match path if necessary.
  if (!empty($pages)) {
    $path = drupal_get_path_alias($_GET['q']);
    // Compare with the internal and path alias (if any).
    $page_match = drupal_match_path($path, $pages);
    if ($path != $_GET['q']) {
      $page_match = $page_match || drupal_match_path($_GET['q'], $pages);
    }
    // When $visibility has a value of 0, the block is displayed on
    // all pages except those listed in $pages. When set to 1, it
    // is displayed only on those pages listed in $pages.
    $page_match = !($visibility xor $page_match);
  }
  else {
    $page_match = TRUE;
  }

  return $page_match;
}